include::utils.adoc[]

= Onboarding a Web App into the K8s Cluster

== Objectives

- onboarding a web app into the K8s Cluster

We will talk about: Containers, Kubernetes, Kubectl, Helm

Estimated time: (?)

---

== 1. Containerizing the Web App

In container-land, it's a recommended practice to have a single process running on each container.
Our web app,  __frontend__ and __backend__, will be deployed using two Pods, each Pod running a single container, each container running a single process.

For the sake of simplicity, we provide two example Dockerfiles for building these images but also the URL to pull images directly.

[TIP]
.Too Lazy to Build? You can pull images from repos:
link:https://ghcr.io/camptocamp/course_docker_frontend[ghcr.io/camptocamp/course_docker_frontend] +
link:https://ghcr.io/camptocamp/course_docker_backend[ghcr.io/camptocamp/course_docker_backend]

For building the images, you `git checkout dockerfile` where we will find `frontend/Dockerfile` and `backend/python/Dockerfile` (you may use `python`, `go` or `java`). 


== 2. Declaring Kubernetes Objects

Onboarding the web app into a K8s cluster requires you to have all app's processes running in Pods.

**Pods?** +
Pods are the pillars of your k8s deployment, they host your running containers.
Each Pod can be seen as a tightly coupled group of containers (or event a single one) wrapped-up to model an application specific logic.
Containers inside a Pod share resources like network interfaces or volumes.
See more link:https://kubernetes.io/docs/concepts/workloads/pods/[official k8s doc on Pods].

**What does this mean in terms of code and workload?** +
Well.. you basically have to declare all Pods, Network Services and any other k8s objects you need to setup your deployment using __yaml__ files.

Let's quickly go through an example for spawning the __backend__ using __yaml__ files. The minimal objects required are a 
link:https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[k8s Deployment]
and a
link:https://kubernetes.io/docs/concepts/services-networking/service/[k8s Service]

First, create __backend__ descriptors:

[source,yaml]
----
# backend-deployment.yaml
include::example$backend-deployment.yaml[]
----

[source,yaml]
----
# backend-service.yaml
include::example$backend-service.yaml[]
----

**NOW** we are ready to onboard our __backend__ into the cluster, wohoo!
So go ahead and apply the object declarations:

``` shell
$ kubectl apply -f backend-service.yaml -f backend-deployment.yaml 
service/backend-service created
service/backend-service created
```

List Pods:

``` shell
$ kubectl get po
NAME                                READY   STATUS    RESTARTS   AGE
backend-deployment-9598dcc4-7mm6z   1/1     Running   0          4s
```

List Services:

``` shell
$ kubectl get service                  
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubernetes        ClusterIP   10.43.0.1       <none>        443/TCP   56m
backend-service   ClusterIP   10.43.205.209   <none>        80/TCP    7s
```

**We have our __backend__ service running in the cluster `o/\o`.**

[TIP] 
====
__backend__ service is only accessible from withing the cluster.
k8s provides a __port-forward__  feature to pipe localhost ports to __Pods__ ports
meant to be used for inspection purposes
====

We can forward `8080` port of our __backend__ to our localhost's `8080` port

```shell
$ export POD_NAME=backend-deployment-9598dcc4-7mm6z
$ kubectl port-forward $POD_NAME 8080:8080
```

Query the API:

```shell
$ curl localhost:8080

{ "products":
  [
    {"name": "geomapfish", "description": "Product description 1"},
    {"name": "georchestra", "description": "Product description 2"},
    {"name": "geonetwork", "description": "Product description 3"}
  ]
}
```

**Wait... What about the __frontend__?**

You can create the __frontend__ deployment and service just as we did for the __backend__ if you want to play a bit more with k8s object declarations.
Fortunately for the continuation of this tutorial we have a shortcut.

== 3. Packaging the Web App for k8s using Helm Chart

Let's talk about package management.
When working with a certain application or bundle of applications (stack) we want deterministic behavior for installing, upgrading, configuring, and removing them.
In the context of k8s, Helm is the best tool there is for this.

**Hands-on the Helm!**

Let's git-checkout the `helm` branch of  link:https://github.com/camptocamp/containers-course-app/[containers-course-app].
Inside `helm/containers-course-app` you will find Helm Chart written to manage the web app package with k8s.

We can first simulate an `install`: 

```shell
$ cd helm/containers-course-app
$ helm install --debug --dry-run test helm/containers-course-app/
```

You may recognize on the output some similarities with the __yaml__ files we created before.

Display default `values`:

```shell
helm show values helm/containers-course-app/
```

Display all content of the Helm Chart:
```
$ helm show all .
```

For the continuation of this tutorial, Helm will be out tool for interacting with the web-app and k8s, all of a sudden life becomes simpler.

**All aboard!**

Install the web-app into k8s cluster using Helm:

```shell
$ cd helm/containers-course-app
$ helm install web-app .
```

For testing the app we should first forward ports of either __frontend__ Pod:

```shell
$ export POD_NAME=frontend-deployment-9598dcc4-7mm6z
$ kubectl port-forward $POD_NAME 8080:8080
```

Open your browser using `http://localhost:8080`

An html catalog of products is displayed? 

Mission Accomplished.
