include::utils.adoc[]

== Creating your Local Kubernetes Cluster

Let's create a minimal working example following the link:https://devops-stack.io/docs/devops-stack/0.32.0/howtos/quickstart_k3s_docker.html[Quickstart for K3s on Docker].

=== 1. Write your Terraform Module for the K8s Cluster

Without getting into too much detail, we will instantiate a Terraform module for link:https://devops-stack.io[the Devops Stack], which will provision the k8s cluster (among other things).

Create a directory, e.g. `my-devops-project`, and create the `main.tf` terraform file in it:

``` hcl
module "cluster" {
  source = "git::https://github.com/camptocamp/devops-stack.git//modules/k3s/docker?ref=v0.30.0"
  cluster_name = "my-cluster"
}
```

Create also a simple output file, named `outputs.tf`:

``` hcl
output "kubeconfig" {
  sensitive = true
  value     = module.cluster.kubeconfig
}

```

=== 2. Deploy the Cluster

Now, let's build the cluster using Terraform:

link:https://learn.hashicorp.com/tutorials/terraform/install-cli[Install Terraform CLI] and then run:

```shell
$ terraform init
$ terraform apply
$ terraform output kubeconfig
```

=== 3. Verify the K8s Cluster API is up

Now the cluster is running using local Docker containers.
To verify this, link:https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[install `kubectl`] to interact with your cluster from your favorite terminal.

Export the path to the kubeconfig file:

```shell
$ export KUBECONFIG=$PWD/kubeconfig.yaml
```

Query the API to list the cluster pods:

```shell
$ kubectl get pods --all-namespaces

NAMESPACE               NAME                                                        READY   STATUS    RESTARTS   AGE
kube-system             local-path-provisioner-6d59f47c7-nq647                      1/1     Running   0          19m
kube-system             metrics-server-7949d47784-4zvd7                             1/1     Running   0          17m
kube-system             coredns-7944c66d8d-x2jlr                                    1/1     Running   0          19m
argocd                  argocd-redis-5644d9f997-4wlgj                               1/1     Running   0          19m
argocd                  argocd-dex-server-b7d78f98-rvh2g                            1/1     Running   0          19m
argocd                  argocd-server-56986c4596-fgbzn                              1/1     Running   0          19m
argocd                  argocd-application-controller-5c5d495d77-nkpvw              1/1     Running   0          19m
argocd                  argocd-repo-server-59f5678fcd-qjs5x                         1/1     Running   0          19m
kube-prometheus-stack   kube-prometheus-stack-operator-54944cdfcc-ddq92             1/1     Running   0          18m
kube-prometheus-stack   kube-prometheus-stack-prometheus-node-exporter-f8jpp        1/1     Running   0          18m
kube-prometheus-stack   kube-prometheus-stack-prometheus-node-exporter-gpqvg        1/1     Running   0          18m
kube-prometheus-stack   kube-prometheus-stack-prometheus-node-exporter-wrn5g        1/1     Running   0          18m
kube-prometheus-stack   kube-prometheus-stack-kube-state-metrics-6b65958dcd-vhd6f   1/1     Running   0          18m
kube-prometheus-stack   kube-prometheus-stack-grafana-5b78d78748-zc8dj              2/2     Running   0          18m
(...)

```

As you may have noticed, inside of the k8s cluster we already have several pods running.
Don't panic, this is normal…
They are meant to handle the app monitoring and operations.

[TIP]
This bundle of apps, all k8s-ready, is what we at link:camptocamp.com[Camptocamp] call link:https://devops-stack.io[the Devops Stack], we will come back to this later, but in short they will provide out-of-the-box the tools you need to manage and operate your app. 

Now, your k8s cluster's API is up and running, let's run something!

=== 4. Deploy a `hello-world` Pod

Let's spawn a very basic, short-lived pod into our k8s cluster.

First, create a `pod-hello-world.yaml` file:

[source,yaml]
----
include::pod-hello-world.yaml[]
----

Proceed to spawn pod:

```shell
$ kubectl apply -f pod-hello-world.yaml
```

Check the output:

```shell
$ kubectl logs hello-world
```

You should see as logged output: "Hello world !!"


[TIP]
.Hip Hip Hurra!
====
If you have reached this part of the tutorial, then kudos to you!
You have deployed a k8s cluster and deployed an app on it!
====


Now, delete the pod, get ready for what's next:

```shell
$ kubectl delete pod hello-world
```

== Next

link:chapter-2.html[Chapter 2: ???]
