apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl4T1RVMk1qQTNNakFlRncweU1UQTBNamN5TWpJeE1USmFGdzB6TVRBME1qVXlNakl4TVRKYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl4T1RVMk1qQTNNakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk5ETWtKN0puUC9PdHVNVnJDdjN6NGI1a3g1VHpiOG80YUxRM1VQOGxFZUsKSERIVWIwMDVFL29ldWhLRVl5bGhzUXhwTFhaek01VWVEdlZCQ2JTc1VoV2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUEvdHpkZXlOTzV5ClFOVzB5NUxnTHFuT2FuZUhSZm1PcXpTL2ZBNjRnSlltQWlCUzZ4emRtNitUUzl2czRXUzUyeEI2OUdYVWhlVkwKSXAwWDdZakxQeW83SEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://172.17.0.8:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 56785cac0484af1e02e2609fb3bc856a
    username: admin
