name: Website

on:
  push:
    branches: 
      - master
env:
  SITE_DIR: 'site'
jobs:
  build_antora:
    name: "Build docs site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0   # Fetch all history for .gitinfo and .lastmod
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: antora-playbook.yml
      - name: "List folder"
        run: |
          ls -ltr $GITHUB_WORKSPACE/build/
      - name: "Upload generated site"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: antora
          path: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"
  deploy_site:
    runs-on: [ubuntu-latest]
    needs: [build_antora]
    name: "Deploy GitHub Pages"
    steps:
     - name: Setup Node.js for use with actions
       uses: actions/setup-node@v1.4.4
       with:
         node-version: 12.x
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download generated Antora docs
       uses: actions/download-artifact@v1
       with:
         name: antora
         path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
     - name: Deploy to GitHub Pages
       uses: JamesIves/github-pages-deploy-action@3.2.1
       with:
        # ACCESS_TOKEN: # optional
        GITHUB_TOKEN: "${{ github.token}}"
        FOLDER: "${{ env.SITE_DIR }}"
        BRANCH: 'gh-pages'
        COMMIT_MESSAGE: "[CI] Publish Documentation for ${{ github.sha }}"
